# Generated by Django 4.2 on 2025-12-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_id', models.IntegerField()),
                ('seat_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seat_availability', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('send_time', models.DateTimeField()),
                ('receive_time', models.DateTimeField()),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup', models.CharField(max_length=100)),
                ('dropoff', models.CharField(max_length=100)),
                ('bus_id', models.IntegerField(blank=True, null=True)),
                ('carpool_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('all_possible_pickup_location', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=50)),
                ('stoppage', models.CharField(max_length=255)),
                ('available_time', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('Bus', 'Bus'), ('Carpool', 'Carpool'), ('Public Transport', 'Public Transport')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField()),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.booking')),
            ],
        ),
        migrations.CreateModel(
            name='LostFound',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('reporter_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('found', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('lost', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('location_reported', models.CharField(max_length=100)),
                ('date_reported', models.DateField()),
                ('reporter_contact', models.CharField(max_length=11)),
                ('item_details', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.service')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_contact', models.CharField(max_length=11)),
                ('incident_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.service')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('category', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.service')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('license_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('schedule', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.service')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.user'),
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('time_taken', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commute.user')),
            ],
            options={
                'unique_together': {('user', 'service')},
            },
        ),
    ]
