# Generated by Django 4.2 on 2025-12-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommuteX_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.user'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.service'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.service'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.service'),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.service'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.booking'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.service'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommuteX_inventory.user'),
        ),
    ]
